
version: '3.8'

services:
  timeeventos-frontend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - VITE_APP_ENV=docker
      - VITE_API_URL=http://timeeventos-backend:3001
      - TZ=America/Bahia
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - scripts_data:/app/scripts
      - logs_data:/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: npm run dev -- --host 0.0.0.0 --port 8080
    restart: unless-stopped
    depends_on:
      - timeeventos-backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    privileged: true

  timeeventos-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - scripts_data:/app/scripts
      - logs_data:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - NODE_ENV=development
      - TZ=America/Bahia
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    privileged: true
    user: root
    cap_add:
      - SYS_TIME
      - SYS_ADMIN

volumes:
  scripts_data:
  logs_data:
