
version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: dashboard-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: dashboard_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Backend Node.js
  backend:
    build: ./backend
    container_name: dashboard-backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/dashboard_db?schema=public
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 24h
      PORT: 3001
      FRONTEND_URL: http://localhost:8080
      LOG_LEVEL: debug
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
      - ./backend/src:/app/src
      - scripts_data:/app/scripts
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dashboard-network
    command: sh -c "npx prisma db push && npm run db:seed && node src/server.js"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: dashboard-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3001
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - scripts_data:/app/scripts
      - logs_data:/app/logs
      - uploads_data:/app/uploads
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - dashboard-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # Proxy reverso Nginx
  nginx:
    image: nginx:alpine
    container_name: dashboard-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - scripts_data:/app/scripts
      - logs_data:/app/logs
      - uploads_data:/app/uploads
    depends_on:
      - frontend
      - backend
    networks:
      - dashboard-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

volumes:
  postgres_data:
    driver: local
  scripts_data:
    driver: local
  logs_data:
    driver: local
  uploads_data:
    driver: local

networks:
  dashboard-network:
    driver: bridge
