
version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: .
    expose:
      - "8080"
    environment:
      - NODE_ENV=development
      - VITE_APP_ENV=docker
      - VITE_API_URL=http://backend:3001
      - VITE_BASE_PATH=/
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - scripts_data:/app/scripts
      - logs_data:/app/logs
    command: npm run dev -- --host 0.0.0.0 --port 8080
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3001"
    volumes:
      - scripts_data:/app/scripts
      - logs_data:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    privileged: true
    user: root

volumes:
  scripts_data:
  logs_data:

networks:
  app-network:
    driver: bridge
