
version: '3.8'

services:
  frontend:
    image: ${REGISTRY_URL}/chrono-frontend:${TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - TZ=America/Bahia
    volumes:
      - ./config/config.js:/app/dist/config.js:ro
      - scripts_data:/app/scripts
      - logs_data:/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: npm run preview -- --host 0.0.0.0 --port 8080
    restart: unless-stopped
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: ${REGISTRY_URL}/chrono-backend:${TAG:-latest}
    ports:
      - "3001:3001"
    volumes:
      - scripts_data:/app/scripts
      - logs_data:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - NODE_ENV=production
      - TZ=America/Bahia
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    privileged: true
    user: root
    cap_add:
      - SYS_TIME
      - SYS_ADMIN

volumes:
  scripts_data:
  logs_data:
